name: ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm lint
      - name: build
        run: pnpm build